#include <stdio.h>
#include <math.h>

int triangle(int val);
int numDivisors(int num);

/*

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/

int main(void) 
{ 
  int x = 500;
  int i = 0;
  int largeNumber = 5000000;
  
  for(i = 1; i <= largeNumber; ++i)
  { 
    if(numDivisors(triangle(i)) > x)
    { 
      printf("triangle # %d has %d divisors\n",triangle(i),numDivisors(triangle(i)));
      printf("(first triangle # with > 500 divisors)\n");
      break;
    }
  } 
 
  return 0;
} 

//gets triangle number of a given val 
int triangle(int val) // the formula to calc a triangle # is val(val+1)/2
{
  return ((pow(val,2) + val) / 2);
}

int numDivisors(int num)
{
  int count = 0;

  // if perfect square, decrease count by 1 since we 
  // don't want to double count the divisor
  if((int)(sqrt(num)) * (int)(sqrt(num)) == num)
  {
    count -= 1;
  }

  // count goes up by 2 since other divisor is on other side of sqrt(num)
  for(int i = 1; i <= sqrt(num); ++i)
  {
    if(num % i == 0)
    {
      count += 2;
    }
  }

  return count;
}
